name: Run tests

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4, "8.0", 8.1]

    steps:
    - uses: actions/checkout@v2
    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
    - uses: php-actions/composer@v6
      with:
        php_version: ${{ matrix.php }}
    - name: Display PHP version
      run: php -v
    - name: Run tests
      run: make test

