name: Run tests

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1', '8.2']

    steps:
    - uses: actions/checkout@v3
    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
    - name: Display PHP version
      run: php -v
    - uses: php-actions/composer@v6
      with:
        php_version: ${{ matrix.php-versions }}
    - name: Run tests
      run: make test

