name: Run tests

on: [push, pull_request]

jobs:
  test:

    # See https://github.com/marketplace/actions/setup-php-action for php version support
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-versions: ['8.2', '8.3', '8.4']

    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
    - uses: php-actions/composer@v6
      with:
        php_version: ${{ matrix.php-versions }}
    - name: Display PHP version
      run: php -v
    - name: Run tests
      run: make test

